// distributors.js — Country / Market / Distributor reference data
// Generated from Distributor_info._1.xlsx (Sheet4: Countries | Customer code |
// Distributor name | Short name), with a `market` field added by grouping each
// country into a region (see main.html's revision comment for the grouping logic).
// Regenerate this file (matching this exact shape) whenever the source workbook
// is updated with new/changed distributors — main.html reads it via loadDataScript(),
// same isolated-iframe pattern as parts.js/users.js/claims.js/Evaluates.js.
var DISTRIBUTOR_DATABASE = [
  {"market": "Americas", "country": "Argentina", "customerCode": "D054PS", "distributorName": "PRODUCT S SOLUTIONS SA", "shortName": "LPS"},
  {"market": "Oceania", "country": "Australia", "customerCode": "D061MA", "distributorName": "MITSUBISHI HEAVY INDUSTRIES AIR-CONDITIONERS AUSTRALIA, PTY. LTD", "shortName": "MHIAA"},
  {"market": "South Asia", "country": "Bangladesh", "customerCode": "D880EE", "distributorName": "ESQUIRE ELECTRONICS LTD.", "shortName": "BANGLA"},
  {"market": "Americas", "country": "Brazil", "customerCode": "D055NV", "distributorName": "NOVAIR IMPORTACAO & EXPORTACAO LTDA", "shortName": "LNOVAI"},
  {"market": "Southeast Asia", "country": "Brunei", "customerCode": "D673BS", "distributorName": "BEE SENG AIR-CONDITIONING & ENGINEERING SDN. BHD", "shortName": "BEESEN"},
  {"market": "Southeast Asia", "country": "Cambodia", "customerCode": "D855HS", "distributorName": "HSC DECOR CENTER CO., LTD.", "shortName": "HSC"},
  {"market": "East Asia", "country": "China", "customerCode": "D086MJ", "distributorName": "MITSUBISHI HEAVY INDUSTRIES JINLING AIR-CONDITIONERS CO.,LTD.", "shortName": "MJA"},
  {"market": "Americas", "country": "Costa Rica", "customerCode": "D506ML", "distributorName": "MULTIFRIO S.A.", "shortName": "LMULTI"},
  {"market": "Middle East & Africa", "country": "Ghana", "customerCode": "D233GH", "distributorName": "PENTRAGG ENGINEERING LTD.", "shortName": "PENTRAGG"},
  {"market": "East Asia", "country": "Hong Kong", "customerCode": "D852MH", "distributorName": "MITSUBISHI HEAVY INDUSTRIES (HK) LIMITED", "shortName": "MHIH"},
  {"market": "South Asia", "country": "India", "customerCode": "D091IA", "distributorName": "INTERNATIONAL AIRCON PVT.LTD.", "shortName": "IAPL"},
  {"market": "South Asia", "country": "India", "customerCode": "D091SV", "distributorName": "SHINRYO SUVIDHA ENGINEERS INDIA PVT. LTD", "shortName": "SUVIDA"},
  {"market": "Southeast Asia", "country": "Indonesia", "customerCode": "D062BS", "distributorName": "PT. BERKAT SARANA AIRCON", "shortName": "BSAIR"},
  {"market": "Southeast Asia", "country": "Indonesia", "customerCode": "D062GB", "distributorName": "PT.GRAHA BERKAT TRADING", "shortName": "GRAHA"},
  {"market": "Middle East & Africa", "country": "Iran", "customerCode": "D098AM", "distributorName": "CHALIAN CORPORATION", "shortName": "CHALIAN"},
  {"market": "East Asia", "country": "Japan", "customerCode": "D081MP", "distributorName": "MITSUBISHI HEAVY INDUSTRIES AIR-CONDITIONING AND REFRIGERATION, LTD.", "shortName": "MTH"},
  {"market": "East Asia", "country": "Japan", "customerCode": "D081MR", "distributorName": "MITSUBISHI HEAVY INDUSTRIES AIR-CONDITIONING AND REFRIGERATION, LTD.", "shortName": ""},
  {"market": "East Asia", "country": "Japan", "customerCode": "D081MT", "distributorName": "MTH", "shortName": ""},
  {"market": "East Asia", "country": "Japan", "customerCode": "D081TC", "distributorName": "T.CHATANI CO.,LTD.", "shortName": "CHATANI"},
  {"market": "Southeast Asia", "country": "Malaysia", "customerCode": "D060IM", "distributorName": "IMZ SDN BHD", "shortName": "IMZ"},
  {"market": "Southeast Asia", "country": "Malaysia", "customerCode": "D060TR", "distributorName": "TRIO ELECTRIC & AUTOMATION (M) SDN BHD", "shortName": "TRIO"},
  {"market": "Americas", "country": "Mexico", "customerCode": "D052CL", "distributorName": "CLIMA EFICIENT DE JAPAN, S.A. DE C.V.", "shortName": "LCLIMA"},
  {"market": "Southeast Asia", "country": "Myanmar", "customerCode": "D095OM", "distributorName": "ONE M (MYANMAR)", "shortName": "ONE M"},
  {"market": "South Asia", "country": "Nepal", "customerCode": "D977AT", "distributorName": "AIRTECH INDUSTRIES PVT. LTD.", "shortName": "AIRTEC"},
  {"market": "South Asia", "country": "Nepal", "customerCode": "D977HT", "distributorName": "AIRTECH INDUSTRIES PVT. LTD.", "shortName": ""},
  {"market": "Oceania", "country": "New Caledonia", "customerCode": "D687NC", "distributorName": "NBK CORPORATION", "shortName": "NBK"},
  {"market": "South Asia", "country": "Pakistan", "customerCode": "D092OR", "distributorName": "ORIENT ELECTRONICS (PVT) LTD.", "shortName": "ORIENT"},
  {"market": "Southeast Asia", "country": "Philippines", "customerCode": "D063MA", "distributorName": "MIT-AIR INC.", "shortName": "MIT AIR"},
  {"market": "Middle East & Africa", "country": "Qatar", "customerCode": "D974TY", "distributorName": "AI TEYSEER AIR CONDITIONING & REFRIGERATION", "shortName": "TEYSER"},
  {"market": "Southeast Asia", "country": "Singapore", "customerCode": "D065KM", "distributorName": "KM MARKETING PTE LTD", "shortName": "KM"},
  {"market": "South Asia", "country": "Sri Lanka", "customerCode": "D094SG", "distributorName": "SINGER (SRI LANKA) PLC.", "shortName": "SINGER"},
  {"market": "East Asia", "country": "Taiwan", "customerCode": "D886TB", "distributorName": "TOYO-BOEKI", "shortName": "TOYO-BOEKI"},
  {"market": "East Asia", "country": "Taiwan", "customerCode": "D886UY", "distributorName": "UP YOUNG CORNERSTONE CORPORATION", "shortName": "UP YOUNG"},
  {"market": "Southeast Asia", "country": "Thailand", "customerCode": "D066MJ", "distributorName": "MAHAJAK AIR CONDITIONERS CO.,LTD.", "shortName": "MAC"},
  {"market": "Southeast Asia", "country": "Thailand", "customerCode": "D066MJ", "distributorName": "MAHAJAK DEVELOPMENT CO.,LTD.", "shortName": "MDC"},
  {"market": "Middle East & Africa", "country": "Turkey", "customerCode": "D090FM", "distributorName": "FORM MHI KLIMA SISTEMLERI SAN. VE TIC.A.S.", "shortName": "FORM"},
  {"market": "Middle East & Africa", "country": "Turkey", "customerCode": "D090TK", "distributorName": "TEKNOSA IC VE DIS TICARET A.S.", "shortName": "TEKNOSA"},
  {"market": "Europe", "country": "United Kingdom", "customerCode": "D044ME", "distributorName": "MHIAE", "shortName": "MHIAE"},
  {"market": "Southeast Asia", "country": "Vietnam", "customerCode": "D084HL", "distributorName": "CONG TY TNHH HAILI", "shortName": "HAILI"},
  {"market": "Southeast Asia", "country": "Vietnam", "customerCode": "D084HT", "distributorName": "HANOI TECHNIQUES JOINT STOCK COMPANY", "shortName": "HATECH"},
  {"market": "Southeast Asia", "country": "Vietnam", "customerCode": "D084VK", "distributorName": "VELK TRADING CORPORATION", "shortName": "VELK"},
  {"market": "Southeast Asia", "country": "Vietnam", "customerCode": "D084VT", "distributorName": "VIETCAN CORPORATION", "shortName": "VTECO"},
];
